workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d{4}-(DEV|PROD)$/'
    - when: never

stages:
  - build

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "$REGISTRY_DOMAIN/development/infrastructure/sql-server-2022-base/sql-server-2022-base"


build_and_push:
  stage: build
  image: docker:29.6.0-cli
  services:
    - name: docker:29.6.0-dind
  tags:
    - shared
  before_script:
    - apk add --no-cache ca-certificates
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      mkdir -p /etc/buildkit
      cat <<EOF > /etc/buildkit/buildkitd.toml
      [registry."$MAIN_DOMAIN"]
        http = false
        insecure = true
      [registry."$REGISTRY_DOMAIN"]
        http = false
        insecure = true
      EOF
      docker buildx create --use --config /etc/buildkit/buildkitd.toml --name custom-builder
  script:
    - export MSSQL_PASSWORD="$CONTAINER_USER_PASSWORD"
    - docker build --provenance=false --platform linux/amd64 --secret id=mssql_password,env=MSSQL_PASSWORD -t "$IMAGE_NAME:$CI_COMMIT_TAG" --push .