name: sql-server

services:
  sql-server:
    build:
      context: .
    secrets:
      - mssql_password
    container_name: sql-server
    restart: unless-stopped
    ports:
      - "2222:22"
      - "1433:1433"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

secrets:
  mssql_password:
    file: ./secrets/mssql_password.txt